# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='disposition',
            field=models.BooleanField(default=True),
        ),
    ]
