# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-29 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_league_disposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('home_won', models.IntegerField()),
                ('home_drawn', models.IntegerField()),
                ('home_lost', models.IntegerField()),
                ('away_won', models.IntegerField()),
                ('away_drawn', models.IntegerField()),
                ('away_lost', models.IntegerField()),
                ('gf', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('movement', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccer.Team')),
            ],
        ),
    ]
